language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4.0
      dist: bionic
      env:
        - analysis=no
        - coverage=no
        - phpunitflags="--stop-on-failure --exclude-group=live"
        - lint="yes"
    - php: 7.4
      dist: bionic
      env:
        - analysis=yes
        - coverage=yes
        - phpunitflags="--stop-on-failure --coverage-clover=clover.xml"

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - if [[ "$coverage" = "no" ]]; then phpenv config-rm xdebug.ini; fi
  - composer install --no-interaction --prefer-dist
  - if [[ "$coverage" = "yes" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ "$coverage" = "yes" ]]; then chmod +x ./cc-test-reporter; fi
  - if [[ "$coverage" = "yes" ]]; then ./cc-test-reporter before-build; fi

script:
  - vendor/bin/parallel-lint .php_cs.dist src tests examples
  - vendor/bin/phpunit $phpunitflags
  - if [[ "$analysis" = "yes" ]]; then vendor/bin/composer-require-checker check ./composer.json; fi
  - if [[ "$analysis" = "yes" ]]; then vendor/bin/psalm --show-info=false --shepherd; fi
  - if [[ "$lint" = "yes" ]]; then vendor/bin/php-cs-fixer fix --allow-risky=yes --no-interaction --dry-run --diff-format=udiff -v; fi
  - if [[ "$lint" = "yes" ]]; then vendor/bin/phpcpd src tests; fi

after_script:
  - if [[ "$coverage" = "yes" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t clover; fi
  - if [[ "$coverage" = "yes" ]]; then vendor/bin/php-coveralls; fi
