language: php
php:
  - 7.4.0
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/parallel-lint .php_cs.dist src tests examples
  - vendor/bin/phpunit --coverage-clover=clover.xml
  - vendor/bin/php-coveralls
  - vendor/bin/composer-require-checker check ./composer.json
  - vendor/bin/psalm --show-info=false --shepherd
  - vendor/bin/php-cs-fixer fix --allow-risky=yes --no-interaction --dry-run --diff-format=udiff -v

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t clover
